[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 800
via_ir = false
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
arc_testnet = "https://rpc.testnet.arc.network"
